import { ImageSourcePropType } from 'react-native';

const images: { [key: string]: ImageSourcePropType } = {
  background: require('../Images/background.png'),
  logo: require('../Images/logo.png'),
  simpleBg: require('../Images/simpleBackground.png'),
  Vector: require('../Images/Vector.png'),
  arrowUp: require('../Images/ArrowUp.png'),
  orLine: require('../Images/orBorder.png'),
  googleIcon: require('../Images/GoogleIcon.png'),
  appleIcon: require('../Images/AppleIcon.png'),
  eyeIcon: require('../Images/eyeIcon.png'),
  backArrow: require('../Images/backArrow.png'),
  success: require('../Images/success.png'),
  Shade: require('../Images/Shade.png'),
  UK: require('../Images/UK.png'),
  line: require('../Images/line.png'),
  camera: require('../Images/camera.png'),
  profGradient: require('../Images/ProfGradient.png'),
  profile: require('../Images/profile.png'),
  secIcon: require('../Images/SecIcon.png'),
  drawerIcon: require('../Images/drawerIcon.png'),
  visa: require('../Images/visa.png'),
  masterCard: require('../Images/masterCard.png'),
  greaterIcon: require('../Images/greaterIcon.png'),
  phone: require('../Images/phone.png'),
  email: require('../Images/email.png'),
  facebook: require('../Images/facebook.png'),
  instagram: require('../Images/instagram.png'),
  twitter: require('../Images/twitter.png'),
  sendBtn: require('../Images/sendBtn.png'),
  voice: require('../Images/voice.png'),
  check: require('../Images/check.png'),
  User: require('../Images/User.png'),
  Location: require('../Images/Location.png'),
  card: require('../Images/card.png'),
  guide: require('../Images/guide.png'),
  cross: require('../Images/cross.png'),
  arrow: require('../Images/arrow.png')
};

export default images;
